
--
-- Tipe Kustom
--
CREATE TYPE public.plan_type AS ENUM (
    'TRIAL',
    'PRO'
);

CREATE TYPE public.transaction_type AS ENUM (
    'Pemasukan',
    'Pengeluaran'
);

--
-- Tabel: profiles
--
CREATE TABLE public.profiles (
    id uuid NOT NULL PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    email character varying,
    plan public.plan_type DEFAULT 'TRIAL'::public.plan_type NOT NULL
);

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Pengguna dapat melihat profil mereka sendiri."
ON public.profiles FOR SELECT
USING (auth.uid() = id);

CREATE POLICY "Pengguna dapat memperbarui profil mereka sendiri."
ON public.profiles FOR UPDATE
USING (auth.uid() = id);

--
-- Tabel: students
--
CREATE TABLE public.students (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    nis text NOT NULL,
    name text NOT NULL,
    class text NOT NULL,
    user_id uuid DEFAULT auth.uid() NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    whatsapp_number text, -- Kolom baru ditambahkan
    UNIQUE (user_id, nis)
);

ALTER TABLE public.students ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Pengguna dapat melihat siswa yang mereka miliki."
ON public.students FOR SELECT
USING (auth.uid() = user_id);

CREATE POLICY "Pengguna dapat menambah siswa untuk akun mereka."
ON public.students FOR INSERT
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Pengguna dapat memperbarui siswa mereka sendiri."
ON public.students FOR UPDATE
USING (auth.uid() = user_id);

CREATE POLICY "Pengguna dapat menghapus siswa mereka sendiri."
ON public.students FOR DELETE
USING (auth.uid() = user_id);


--
-- Tabel: transactions
--
CREATE TABLE public.transactions (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    type public.transaction_type NOT NULL,
    description text NOT NULL,
    amount real NOT NULL,
    student_id uuid NOT NULL REFERENCES public.students(id) ON DELETE CASCADE,
    user_id uuid DEFAULT auth.uid() NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE
);

ALTER TABLE public.transactions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Pengguna dapat melihat transaksi siswa mereka."
ON public.transactions FOR SELECT
USING (auth.uid() = user_id);

CREATE POLICY "Pengguna dapat menyisipkan transaksi untuk siswa mereka."
ON public.transactions FOR INSERT
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Pengguna dapat menghapus transaksi siswa mereka."
ON public.transactions FOR DELETE
USING (auth.uid() = user_id);

--
-- Tabel: activation_codes
--
CREATE TABLE public.activation_codes (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    code text not null unique,
    is_used boolean not null default false,
    used_by uuid null references public.profiles(id),
    used_at timestamp with time zone
);

ALTER TABLE public.activation_codes ENABLE ROW LEVEL SECURITY;

-- Di lingkungan produksi, admin harus memiliki peran khusus.
-- Untuk kesederhanaan, kita izinkan semua pengguna terautentikasi untuk membaca.
CREATE POLICY "Pengguna terautentikasi dapat melihat kode."
ON public.activation_codes FOR SELECT
USING (auth.role() = 'authenticated');

-- Hanya service_role (dari server/edge function) yang bisa membuat/mengubah kode.
-- Untuk admin panel di klien, Anda memerlukan RPC dengan `security definer`.
-- Namun untuk sekarang, kita nonaktifkan insert/update dari klien secara langsung.
-- CREATE POLICY "Admin can create codes" ON activation_codes FOR INSERT WITH CHECK (false);
-- CREATE POLICY "Admin can update codes" ON activation_codes FOR UPDATE USING (false);


--
-- Fungsi RPC untuk aktivasi
--
CREATE OR REPLACE FUNCTION activate_account(p_code text, p_user_id uuid)
RETURNS SETOF public.profiles
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_code_id bigint;
BEGIN
  -- 1. Temukan dan kunci baris kode aktivasi
  SELECT id INTO v_code_id
  FROM public.activation_codes
  WHERE code = p_code AND is_used = false
  FOR UPDATE;

  -- 2. Jika kode tidak ada atau sudah digunakan, lemparkan error
  IF v_code_id IS NULL THEN
    RAISE EXCEPTION 'Kode aktivasi tidak valid atau telah digunakan.';
  END IF;

  -- 3. Perbarui tabel kode aktivasi
  UPDATE public.activation_codes
  SET 
    is_used = true,
    used_by = p_user_id,
    used_at = now()
  WHERE id = v_code_id;

  -- 4. Perbarui paket pengguna menjadi 'PRO'
  UPDATE public.profiles
  SET plan = 'PRO'
  WHERE id = p_user_id;

  -- 5. Kembalikan profil yang diperbarui
  RETURN QUERY
  SELECT * FROM public.profiles WHERE id = p_user_id;
END;
$$;


--
-- Initial Data
--
-- Anda dapat menambahkan data awal di sini jika diperlukan.
-- contoh: INSERT INTO public.some_table (name) VALUES ('Initial Data');
