-- ==========================================================
-- BLUEPRINT DATABASE TABUNGIN (SUPABASE)
-- Copy dan Paste seluruh kode ini ke SQL Editor di Supabase
-- ==========================================================

-- 1. Tabel Profiles (Informasi Guru/Admin)
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL PRIMARY KEY,
  email TEXT,
  role TEXT DEFAULT 'USER' CHECK (role IN ('ADMIN', 'USER')),
  plan TEXT DEFAULT 'TRIAL' CHECK (plan IN ('TRIAL', 'PRO')),
  school_name TEXT,
  school_code TEXT UNIQUE,
  custom_quota INTEGER DEFAULT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Tabel Students (Data Siswa)
CREATE TABLE IF NOT EXISTS public.students (
  id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL PRIMARY KEY,
  nis TEXT NOT NULL,
  name TEXT NOT NULL,
  class TEXT NOT NULL,
  whatsapp_number TEXT,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(nis, user_id)
);

-- 3. Tabel Transactions (Riwayat Tabungan)
CREATE TABLE IF NOT EXISTS public.transactions (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  student_id UUID REFERENCES public.students(id) ON DELETE CASCADE NOT NULL,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  amount BIGINT NOT NULL,
  type TEXT NOT NULL CHECK (type IN ('Pemasukan', 'Pengeluaran')),
  description TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Tabel Activation Codes (Kode Premium)
CREATE TABLE IF NOT EXISTS public.activation_codes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT UNIQUE NOT NULL,
  is_used BOOLEAN DEFAULT FALSE,
  used_by UUID REFERENCES public.profiles(id),
  used_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ==========================================================
-- KEAMANAN (RLS - ROW LEVEL SECURITY)
-- ==========================================================

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.students ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.activation_codes ENABLE ROW LEVEL SECURITY;

-- Kebijakan Profil: User bisa baca & ubah profil sendiri
CREATE POLICY "Users can view own profile" ON public.profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Users can update own profile" ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- Kebijakan Siswa: Guru lihat muridnya, Siswa lihat dirinya sendiri
CREATE POLICY "Teachers can manage own students" ON public.students 
FOR ALL USING (auth.uid() = user_id OR auth.uid() = id);

-- Kebijakan Transaksi: Guru manage transaksi muridnya, Siswa baca transaksinya sendiri
CREATE POLICY "Teachers can manage transactions" ON public.transactions 
FOR ALL USING (auth.uid() = user_id OR auth.uid() = student_id);

-- Kebijakan Kode: Admin manage kode, Guru bisa baca untuk aktivasi
CREATE POLICY "Admins can manage codes" ON public.activation_codes FOR ALL USING (
  EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'ADMIN')
);
CREATE POLICY "Users can view codes for check" ON public.activation_codes FOR SELECT USING (true);

-- ==========================================================
-- FUNGSI & TRIGGER OTOMATIS
-- ==========================================================

-- Fungsi untuk otomatis membuat profil saat Guru daftar (Signup)
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  -- Jangan buat profil untuk shadow email milik siswa (.supabase.user)
  IF new.email NOT LIKE '%.supabase.user' THEN
    INSERT INTO public.profiles (id, email, role, plan)
    VALUES (new.id, new.email, 'USER', 'TRIAL');
  END IF;
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger saat insert ke auth.users
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- Fungsi RPC untuk Aktivasi Akun ke PRO
CREATE OR REPLACE FUNCTION public.activate_account(p_code TEXT, p_user_id UUID)
RETURNS VOID AS $$
BEGIN
    IF EXISTS (SELECT 1 FROM public.activation_codes WHERE code = p_code AND is_used = FALSE) THEN
        -- Update kode jadi terpakai
        UPDATE public.activation_codes 
        SET is_used = TRUE, used_by = p_user_id, used_at = now() 
        WHERE code = p_code;
        
        -- Upgrade plan guru
        UPDATE public.profiles 
        SET plan = 'PRO' 
        WHERE id = p_user_id;
    ELSE
        RAISE EXCEPTION 'invalid_or_used_code';
    END IF;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ==========================================================
-- SOLUSI ERROR "PROFIL TIDAK DITEMUKAN"
-- ==========================================================
-- Jika Anda melihat error tersebut, cari ID Anda di menu "Authentication" > "Users",
-- lalu jalankan perintah di bawah ini (hilangkan tanda -- dan ganti ID-nya):

-- INSERT INTO public.profiles (id, email, role, plan) 
-- VALUES ('GANTI-DENGAN-ID-USER-ANDA', 'email-anda@gmail.com', 'ADMIN', 'PRO');
