-- ==========================================
-- TABUNGIN FULL DATABASE BLUEPRINT (v1.2)
-- ==========================================

-- 1. TABEL PROFIL (Guru & Kantin)
CREATE TABLE IF NOT EXISTS public.profiles (
  id uuid REFERENCES auth.users ON DELETE CASCADE NOT NULL PRIMARY KEY,
  email text,
  role text DEFAULT 'ADMIN' CHECK (role IN ('ADMIN', 'CANTINE')),
  plan text DEFAULT 'TRIAL' CHECK (plan IN ('TRIAL', 'PRO')),
  school_name text,
  school_code text UNIQUE,
  custom_quota integer DEFAULT NULL,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. TABEL SISWA
CREATE TABLE IF NOT EXISTS public.students (
  id uuid REFERENCES auth.users ON DELETE CASCADE NOT NULL PRIMARY KEY,
  nis text NOT NULL,
  name text NOT NULL,
  class text NOT NULL,
  whatsapp_number text,
  user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(nis, user_id)
);

-- 3. TABEL TRANSAKSI (Tabungan, Belanja, Tarik Tunai)
CREATE TABLE IF NOT EXISTS public.transactions (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  student_id uuid REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  amount bigint NOT NULL,
  type text NOT NULL CHECK (type IN ('Pemasukan', 'Pengeluaran')),
  category text DEFAULT 'TABUNGAN' CHECK (category IN ('TABUNGAN', 'BELANJA_KANTIN', 'TARIK_TUNAI')),
  description text,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. TABEL KODE AKTIVASI
CREATE TABLE IF NOT EXISTS public.activation_codes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code text UNIQUE NOT NULL,
  is_used boolean DEFAULT false,
  used_by uuid REFERENCES public.profiles(id),
  used_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ==========================================
-- KEAMANAN (RLS - Row Level Security)
-- ==========================================

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.students ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.activation_codes ENABLE ROW LEVEL SECURITY;

-- Kebijakan Profil
CREATE POLICY "User can view own profile" ON public.profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "User can update own profile" ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- Kebijakan Guru (Admin)
CREATE POLICY "Guru can manage their students" ON public.students FOR ALL USING (user_id = auth.uid());
CREATE POLICY "Guru can manage transactions" ON public.transactions FOR ALL USING (user_id = auth.uid());

-- Kebijakan Siswa
CREATE POLICY "Student can view own data" ON public.students FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Student can view own transactions" ON public.transactions FOR SELECT USING (student_id = auth.uid());

-- Kebijakan Kantin (Baru)
CREATE POLICY "Cantine can view students in same school" ON public.students FOR SELECT 
USING (
  EXISTS (
    SELECT 1 FROM public.profiles p 
    WHERE p.id = auth.uid() AND p.role = 'CANTINE' 
    AND p.school_code = (SELECT school_code FROM public.profiles WHERE id = public.students.user_id)
  )
);

CREATE POLICY "Cantine can record sales" ON public.transactions FOR INSERT 
WITH CHECK (
  EXISTS (
    SELECT 1 FROM public.profiles p 
    WHERE p.id = auth.uid() AND p.role = 'CANTINE'
  )
);

-- ==========================================
-- OTOMATISASI (Trigger & Functions)
-- ==========================================

-- Fungsi Create Profile saat Signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  -- Hanya buat profil jika email TIDAK berakhiran .supabase.user (bukan siswa)
  IF NEW.email NOT LIKE '%.supabase.user' THEN
    INSERT INTO public.profiles (id, email, role)
    VALUES (NEW.id, NEW.email, 'ADMIN');
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- Fungsi RPC Aktivasi Akun
CREATE OR REPLACE FUNCTION public.activate_account(p_code text, p_user_id uuid)
RETURNS void AS $$
DECLARE
    code_record RECORD;
BEGIN
    SELECT * INTO code_record FROM public.activation_codes 
    WHERE code = p_code AND is_used = false;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'invalid_or_used_code';
    END IF;

    UPDATE public.profiles SET plan = 'PRO' WHERE id = p_user_id;
    UPDATE public.activation_codes SET is_used = true, used_by = p_user_id, used_at = now() WHERE code = p_code;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;