-- BLUEPRINT DATABASE TABUNGIN (VERSI 2.0 - DENGAN DUKUNGAN KANTIN)
-- Jalankan kode ini di SQL Editor Supabase Proyek Baru Anda

-- 1. Tabel Profil (Untuk Guru/Admin dan Kantin)
create table public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  email text unique not null,
  role text check (role in ('ADMIN', 'CANTINE')) default 'ADMIN',
  school_name text,
  school_code text unique, -- Kode unik sekolah (huruf kecil, tanpa spasi)
  plan text check (plan in ('TRIAL', 'PRO')) default 'TRIAL',
  custom_quota integer default null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Tabel Siswa
create table public.students (
  id uuid references auth.users on delete cascade not null primary key,
  nis text not null,
  name text not null,
  class text not null,
  whatsapp_number text,
  user_id uuid references public.profiles(id) on delete cascade not null, -- Guru/Admin yang mengelola
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(nis, user_id) -- NIS unik per sekolah
);

-- 3. Tabel Transaksi
create table public.transactions (
  id uuid default gen_random_uuid() primary key,
  student_id uuid references public.students(id) on delete cascade not null,
  user_id uuid references public.profiles(id) on delete cascade not null, -- Guru atau Kantin yang memproses
  amount integer not null,
  type text check (type in ('Pemasukan', 'Pengeluaran')) not null,
  description text,
  category text check (category in ('TABUNGAN', 'BELANJA_KANTIN', 'TARIK_TUNAI')) default 'TABUNGAN',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Tabel Kode Aktivasi Premium
create table public.activation_codes (
  id bigint generated by default as identity primary key,
  code text unique not null,
  is_used boolean default false,
  used_by uuid references public.profiles(id),
  used_at timestamp with time zone,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 5. Aktifkan RLS (Row Level Security)
alter table public.profiles enable row level security;
alter table public.students enable row level security;
alter table public.transactions enable row level security;
alter table public.activation_codes enable row level security;

-- 6. Aturan Kebijakan (RLS Policies)

-- PROFILES: User bisa baca & ubah data sendiri
create policy "Users can read own profile" on public.profiles for select using (auth.uid() = id);
create policy "Users can update own profile" on public.profiles for update using (auth.uid() = id);

-- STUDENTS: 
-- 1. Guru bisa kelola murid miliknya
create policy "Teachers can manage own students" on public.students for all using (auth.uid() = user_id);
-- 2. Kantin bisa baca data murid di sekolah yang sama
create policy "Cantine can read students in same school" on public.students for select using (
  exists (
    select 1 from public.profiles p1
    join public.profiles p2 on p1.school_code = p2.school_code
    where p1.id = auth.uid() and p2.id = public.students.user_id
  )
);

-- TRANSACTIONS:
-- 1. Guru/Kantin bisa baca transaksi yang mereka proses
create policy "Users can read transactions they processed" on public.transactions for select using (auth.uid() = user_id);
-- 2. Siswa bisa baca transaksi miliknya sendiri
create policy "Students can read own transactions" on public.transactions for select using (auth.uid() = student_id);
-- 3. Guru/Kantin bisa tambah transaksi
create policy "Authorized users can insert transactions" on public.transactions for insert with check (
  auth.uid() = user_id or auth.uid() = student_id
);

-- 7. Fungsi RPC untuk Aktivasi Akun
create or replace function public.activate_account(p_code text, p_user_id uuid)
returns void as $$
begin
  if exists (select 1 from public.activation_codes where code = p_code and is_used = false) then
    update public.activation_codes 
    set is_used = true, used_by = p_user_id, used_at = now() 
    where code = p_code;
    
    update public.profiles 
    set plan = 'PRO' 
    where id = p_user_id;
  else
    raise exception 'invalid_or_used_code';
  end if;
end;
$$ language plpgsql security definer;

-- 8. Fungsi & Trigger untuk Otomatisasi Profil
create or replace function public.handle_new_user()
returns trigger
security definer set search_path = public
as $$
begin
  -- Jangan buat profil jika user adalah akun bayangan siswa (.supabase.user)
  if new.email not like '%.supabase.user' then
    insert into public.profiles (id, email, role)
    values (new.id, new.email, 'ADMIN');
  end if;
  return new;
end;
$$ language plpgsql;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- INFORMASI PENTING:
-- Jika Anda sudah terlanjur mendaftar sebelum menjalankan SQL ini, profil Anda tidak akan muncul.
-- Hapus tanda komentar pada perintah di bawah ini, ganti emailnya, dan jalankan perintah ini:
/*
insert into public.profiles (id, email, role)
select id, email, 'ADMIN' from auth.users 
where email = 'EMAIL_GURU_ANDA@GMAIL.COM'
on conflict (id) do nothing;
*/