-- ### TABLES ###

-- PROFILES
-- Stores public user data.
create table profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  email text,
  plan text default 'TRIAL' check (plan in ('TRIAL', 'PRO')),
  role text default 'USER' check (role in ('ADMIN', 'USER')),
  school_name text,
  school_code text
);
-- Add UNIQUE constraint to school_code
alter table profiles add constraint profiles_school_code_key unique (school_code);
-- Comments
comment on table profiles is 'Public user profiles, linked to auth.users.';


-- STUDENTS
-- Stores student information, linked to a user (teacher/admin).
create table students (
  id uuid primary key references auth.users(id) on delete cascade,
  user_id uuid references auth.users (id) on delete cascade not null,
  nis text not null,
  name text not null,
  class text not null,
  whatsapp_number text,
  created_at timestamptz default now()
);
-- Add UNIQUE constraint to nis for a given user
alter table students add constraint students_user_id_nis_key unique (user_id, nis);
-- Comments
comment on table students is 'Student profiles, managed by a user (teacher/admin).';


-- TRANSACTIONS
-- Stores all financial transactions for each student.
create table transactions (
  id uuid primary key default gen_random_uuid(),
  student_id uuid references students (id) on delete cascade not null,
  user_id uuid references auth.users (id) on delete cascade not null,
  created_at timestamptz default now(),
  type text not null check (type in ('Pemasukan', 'Pengeluaran')),
  description text not null,
  amount numeric not null
);
-- Comments
comment on table transactions is 'Financial records for each student.';


-- ACTIVATION CODES
-- Stores codes for upgrading users to PRO plan.
create table activation_codes (
  id bigint primary key generated by default as identity,
  code text not null unique,
  created_at timestamptz default now(),
  is_used boolean default false,
  used_by uuid references auth.users (id),
  used_at timestamptz
);
-- Comments
comment on table activation_codes is 'Activation codes for PRO plan upgrades.';


-- ### RLS (ROW LEVEL SECURITY) ###

-- Enable RLS for all tables
alter table profiles enable row level security;
alter table students enable row level security;
alter table transactions enable row level security;
alter table activation_codes enable row level security;

-- Clear existing policies before creating new ones
DROP POLICY IF EXISTS "Users can view their own profile." ON profiles;
DROP POLICY IF EXISTS "Users can update their own profile." ON profiles;
DROP POLICY IF EXISTS "Users can manage their own students." ON students;
DROP POLICY IF EXISTS "Users can manage their own transactions." ON transactions;
DROP POLICY IF EXISTS "Users can view all codes" ON activation_codes;
DROP POLICY IF EXISTS "Users can update codes" ON activation_codes;


-- POLICIES for PROFILES
create policy "Users can view their own profile."
on profiles for select using (auth.uid() = id);

create policy "Users can update their own profile."
on profiles for update using (auth.uid() = id);


-- POLICIES for STUDENTS
create policy "Users can manage their own students."
on students for all using (auth.uid() = user_id);


-- POLICIES for TRANSACTIONS
create policy "Users can manage their own transactions."
on transactions for all using (auth.uid() = user_id);


-- POLICIES for ACTIVATION_CODES
-- Admins can do anything
create policy "Admins can manage activation codes."
on activation_codes for all using (
  exists (
    select 1 from profiles where id = auth.uid() and role = 'ADMIN'
  )
);
-- Non-admins can only read codes, not see who used them
create policy "Users can view activation codes."
on activation_codes for select using (true);


-- ### DB FUNCTIONS (RPC) ###

-- Function to activate a PRO account
create or replace function activate_account(p_code text, p_user_id uuid)
returns void as $$
declare
  code_id bigint;
begin
  -- Check if the code is valid and not used, and get its ID
  select id into code_id
  from public.activation_codes
  where code = p_code and is_used = false;

  -- If code is not found, raise an exception
  if code_id is null then
    raise exception 'invalid_or_used_code';
  end if;

  -- Update the user's plan to 'PRO'
  update public.profiles
  set plan = 'PRO'
  where id = p_user_id;

  -- Mark the code as used
  update public.activation_codes
  set 
    is_used = true,
    used_by = p_user_id,
    used_at = now()
  where id = code_id;
end;
$$ language plpgsql security definer;


-- ### TRIGGERS ###

-- Trigger to create a profile when a new user signs up
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email)
  values (new.id, new.email);
  return new;
end;
$$ language plpgsql security definer;

-- Drop existing trigger if it exists
drop trigger if exists on_auth_user_created on auth.users;

-- Create the trigger
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Grant usage on schema public to supabase_auth_admin
grant usage on schema public to supabase_auth_admin;
grant all on all tables in schema public to supabase_auth_admin;
grant all on all functions in schema public to supabase_auth_admin;
grant all on all sequences in schema public to supabase_auth_admin;