--
-- Initial schema
--
create table "public"."students" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "nis" text not null,
    "name" text not null,
    "class" text not null,
    "whatsapp_number" text,
    "user_id" uuid not null
);


alter table "public"."students" enable row level security;

create table "public"."transactions" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "type" text not null,
    "description" text not null,
    "amount" real not null,
    "student_id" uuid,
    "user_id" uuid
);


alter table "public"."transactions" enable row level security;

create table "public"."profiles" (
    "id" uuid not null,
    "email" text,
    "plan" text default 'TRIAL'::text,
    "role" text default 'USER'::text
);


alter table "public"."profiles" enable row level security;

create table "public"."activation_codes" (
    "id" bigint generated by default as identity,
    "created_at" timestamp with time zone not null default now(),
    "code" text not null,
    "is_used" boolean not null default false,
    "used_by" uuid,
    "used_at" timestamp with time zone
);

alter table "public"."activation_codes" enable row level security;

CREATE UNIQUE INDEX students_nis_key ON public.students USING btree (nis);

CREATE UNIQUE INDEX students_pkey ON public.students USING btree (id);

CREATE UNIQUE INDEX transactions_pkey ON public.transactions USING btree (id);

CREATE UNIQUE INDEX profiles_pkey ON public.profiles USING btree (id);

CREATE UNIQUE INDEX activation_codes_pkey ON public.activation_codes USING btree (id);

CREATE UNIQUE INDEX activation_codes_code_key ON public.activation_codes USING btree (code);

alter table "public"."students" add constraint "students_pkey" PRIMARY KEY using index "students_pkey";

alter table "public"."transactions" add constraint "transactions_pkey" PRIMARY KEY using index "transactions_pkey";

alter table "public"."students" add constraint "students_nis_key" UNIQUE using index "students_nis_key";

alter table "public"."students" add constraint "students_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."students" validate constraint "students_user_id_fkey";

alter table "public"."transactions" add constraint "transactions_student_id_fkey" FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE not valid;

alter table "public"."transactions" validate constraint "transactions_student_id_fkey";

alter table "public"."transactions" add constraint "transactions_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE SET NULL not valid;

alter table "public"."transactions" validate constraint "transactions_user_id_fkey";

alter table "public"."profiles" add constraint "profiles_pkey" PRIMARY KEY using index "profiles_pkey";

alter table "public"."profiles" add constraint "profiles_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."profiles" validate constraint "profiles_id_fkey";

alter table "public"."activation_codes" add constraint "activation_codes_pkey" PRIMARY KEY using index "activation_codes_pkey";

alter table "public"."activation_codes" add constraint "activation_codes_code_key" UNIQUE using index "activation_codes_code_key";

alter table "public"."activation_codes" add constraint "activation_codes_used_by_fkey" FOREIGN KEY (used_by) REFERENCES auth.users(id) ON DELETE SET NULL not valid;

alter table "public"."activation_codes" validate constraint "activation_codes_used_by_fkey";


--
-- Handle new user
--
create function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, email)
  values (new.id, new.email);
  return new;
end;
$$;

--
-- Trigger to handle new user
--
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

--
-- Activate account function
--
CREATE OR REPLACE FUNCTION activate_account(p_code TEXT, p_user_id UUID)
RETURNS JSON
LANGUAGE plpgsql
AS $$
DECLARE
    v_code_id INT;
    v_profile RECORD;
BEGIN
    -- Find the code and lock it
    SELECT id INTO v_code_id FROM activation_codes WHERE code = p_code AND NOT is_used FOR UPDATE;

    -- If code not found or already used, raise an exception
    IF v_code_id IS NULL THEN
        RAISE EXCEPTION 'Invalid or already used activation code';
    END IF;

    -- Update the activation code
    UPDATE activation_codes
    SET is_used = TRUE, used_by = p_user_id, used_at = NOW()
    WHERE id = v_code_id;

    -- Update the user's profile
    UPDATE profiles
    SET plan = 'PRO'
    WHERE id = p_user_id;

    -- Retrieve the updated profile to return
    SELECT * INTO v_profile FROM profiles WHERE id = p_user_id;

    -- Return the profile as JSON
    RETURN row_to_json(v_profile);
END;
$$;


-- Helper function to get user role
CREATE OR REPLACE FUNCTION get_user_role()
RETURNS TEXT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_role TEXT;
BEGIN
  SELECT role INTO v_role FROM profiles WHERE id = auth.uid();
  RETURN v_role;
END;
$$;


--
-- RLS policies
--

-- RLS for students table
create policy "Users can manage their own students"
on "public"."students" for all
using ( auth.uid() = user_id );

-- RLS for transactions table
create policy "Users can manage transactions for their own students"
on "public"."transactions" for all
using ( auth.uid() = user_id );

-- RLS for profiles table
create policy "Users can view their own profile"
on "public"."profiles" for select
using ( auth.uid() = id );

create policy "Admins can view all profiles"
on "public"."profiles" for select
to authenticated
using ( get_user_role() = 'ADMIN' );

create policy "Users can update their own profile"
on "public"."profiles" for update
using ( auth.uid() = id );

create policy "Admins can update all profiles"
on "public"."profiles" for update
to authenticated
using ( get_user_role() = 'ADMIN' );

-- RLS for activation_codes table
create policy "Admins can manage activation codes"
on "public"."activation_codes" for all
to authenticated
using ( get_user_role() = 'ADMIN' );

create policy "Users can view their own used codes"
on "public"."activation_codes" for select
to authenticated
using ( used_by = auth.uid() );
