
-- Initial Schema for Tabungin App

-- 1. Create profiles table
CREATE TABLE IF NOT EXISTS public.profiles (
    id uuid NOT NULL PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    email character varying,
    plan text DEFAULT 'TRIAL'::text,
    role text DEFAULT 'USER'::text NOT NULL
);
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- 2. Create students table
CREATE TABLE IF NOT EXISTS public.students (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now(),
    nis text NOT NULL UNIQUE,
    name text NOT NULL,
    class text,
    user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
    whatsapp_number text
);
ALTER TABLE public.students ENABLE ROW LEVEL SECURITY;

-- 3. Create transactions table
CREATE TABLE IF NOT EXISTS public.transactions (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now(),
    type text,
    description text,
    amount real NOT NULL,
    student_id uuid REFERENCES public.students(id) ON DELETE CASCADE,
    user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE
);
ALTER TABLE public.transactions ENABLE ROW LEVEL SECURITY;


-- 4. Create activation_codes table
CREATE TABLE IF NOT EXISTS public.activation_codes (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default now() not null,
    code text not null unique,
    is_used boolean default false not null,
    used_at timestamp with time zone,
    used_by uuid references auth.users(id)
);
ALTER TABLE public.activation_codes ENABLE ROW LEVEL SECURITY;


-- 5. Create storage buckets
INSERT INTO storage.buckets (id, name, public)
VALUES ('avatars', 'avatars', true)
ON CONFLICT (id) DO NOTHING;

-- 6. RPC function to activate account
CREATE OR REPLACE FUNCTION public.activate_account(p_code text, p_user_id uuid)
RETURNS SETOF profiles
LANGUAGE plpgsql
AS $$
BEGIN
  -- Update activation code
  UPDATE public.activation_codes
  SET 
    is_used = true,
    used_at = now(),
    used_by = p_user_id
  WHERE code = p_code AND is_used = false;

  -- If update was successful, update the user's plan
  IF FOUND THEN
    RETURN QUERY
    UPDATE public.profiles
    SET plan = 'PRO'
    WHERE id = p_user_id
    RETURNING *;
  END IF;
END;
$$;


-- 7. RLS Policies

-- Profiles RLS
CREATE POLICY "Allow authenticated users to see their own profile" ON public.profiles
FOR SELECT USING (auth.uid() = id);

CREATE POLICY "Allow authenticated users to update their own profile" ON public.profiles
FOR UPDATE USING (auth.uid() = id);

CREATE POLICY "Allow admin to read all profiles" ON public.profiles
FOR SELECT TO authenticated
USING (
    (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'ADMIN'
);

-- Students RLS
CREATE POLICY "Allow authenticated users to manage their own students" ON public.students
FOR ALL USING (auth.uid() = user_id);

-- Transactions RLS
CREATE POLICY "Allow authenticated users to manage their own transactions" ON public.transactions
FOR ALL USING (auth.uid() = user_id);

-- Activation Codes RLS
CREATE POLICY "Allow admin users to manage activation codes" ON public.activation_codes
FOR ALL
USING (
    (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'ADMIN'
)
WITH CHECK (
    (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'ADMIN'
);

CREATE POLICY "Allow authenticated users to read available codes" ON public.activation_codes
FOR SELECT TO authenticated
USING (is_used = false);

-- Avatars Storage RLS
CREATE POLICY "Allow authenticated users to manage their own avatars" ON storage.objects
FOR ALL
USING (bucket_id = 'avatars' AND auth.uid() = owner)
WITH CHECK (bucket_id = 'avatars' AND auth.uid() = owner);
